server {
    listen 443 ssl;
    http2 on;

    server_name _;

    root /var/www/html;
    index index.php index.html index.htm;

    ssl_certificate     /etc/nginx/certs/local.crt;
    ssl_certificate_key /etc/nginx/certs/local.key;

    client_max_body_size 100m;

    location / {
        try_files $uri $uri/ /bitrix/urlrewrite.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;

        fastcgi_param HTTPS on;
        fastcgi_param SERVER_PORT 443;
        fastcgi_param REQUEST_SCHEME https;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;

        fastcgi_param PHP_VALUE "max_execution_time=120";
    }

    location ~* ^/upload/.*\.php$ {
        deny all;
    }

    location ~ /\. {
        deny all;
    }

    location ~* \.(svg|png|jpe?g|gif|webp|avif|ico|css|js|mjs|json|xml|txt|pdf|eot|otf|ttf|ttc|woff2?|mp4|mov|webm|mp3|wav|ogg)$ {
        expires 0;
        add_header Cache-Control "max-age=0, must-revalidate";
        try_files $uri =404;
    }
}
