; Для установки Bitrix значения увеличены.
; После установки при необходимости можно уменьшить max_execution_time до 120.
memory_limit = 1024M
upload_max_filesize = 200M
post_max_size = 200M
max_execution_time = 600
max_input_time = 600
max_input_vars = 10000
short_open_tag = On
date.timezone = Europe/Moscow

display_errors = On
display_startup_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
log_errors = On

sendmail_path = "/usr/bin/msmtp -t --read-envelope-from"
